# Generated by Django 4.0.1 on 2022-02-14 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeprojects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='actvie',
            field=models.BooleanField(default=True),
        ),
    ]
