# Generated by Django 4.0.1 on 2022-02-14 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeprojects', '0002_task_actvie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='actvie',
            new_name='activate',
        ),
    ]
