# Generated by Django 4.0.1 on 2022-02-14 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeprojects', '0003_rename_actvie_task_activate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='activate',
            new_name='active',
        ),
    ]
