# Generated by Django 4.0.1 on 2022-02-14 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeprojects', '0004_rename_activate_task_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='name',
            field=models.CharField(default='None', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tool',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='homeprojects.task'),
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='homeprojects.task')),
            ],
        ),
    ]
