# Generated by Django 4.0.2 on 2022-02-18 03:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeprojects', '0006_alter_task_cadence_alter_task_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='time_estimate',
            field=models.DurationField(default=datetime.timedelta(seconds=1)),
            preserve_default=False,
        ),
    ]
