# Generated by Django 4.0.2 on 2022-02-18 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeprojects', '0007_step_time_estimate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='time_estimate',
        ),
    ]
